### ISSUE TITLE
Ignore linting in static folder

### ISSUE THREAD

**Issue by jgauna** [javascriptlabs/hapi-boilerplate#1]
Do you have a way to do this? Thanks.

**Comment by cypherq** [comment]
@jgauna remove line `16` and `17` from `gulp/scripts.js` so content of `static` directory won't be piped to `gulp-jshint` plugin:

https://github.com/javascriptlabs/hapi-boilerplate/blob/master/gulp/scripts.js#L16
https://github.com/javascriptlabs/hapi-boilerplate/blob/master/gulp/scripts.js#L17

You can also remove line `15` if you want to turn of code style checking:

https://github.com/javascriptlabs/hapi-boilerplate/blob/master/gulp/scripts.js#L15

**Comment by jgauna** [comment]
@cypherq Thanks for that ! I don't know how I didn't see that :smile: 

Regards

**Comment by cypherq** [comment]
@jgauna no problem at all, I'm glad I was able to help you.
